// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package mockschema

import (
	"time"
)

type MeResponse struct {
	Tid  string `json:"tid"`
	User User   `json:"user"`
}

type MockEntity struct {
	ID       string    `json:"id"`
	String   string    `json:"string"`
	Integer  int       `json:"integer"`
	Float    float64   `json:"float"`
	Boolean  bool      `json:"boolean"`
	DateTime time.Time `json:"dateTime"`
	Object   Object    `json:"object"`
}

type MockEntityResponse struct {
	Tid    string     `json:"tid"`
	Entity MockEntity `json:"entity"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
